---
- name: install epel repo
  yum: name=epel-release state=present

- name: download cobbler repo
  get_url:
    url: http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler28/CentOS_7/home:libertas-ict:cobbler28.repo
    dest: /etc/yum.repos.d/cobbler28.repo

- name: uncomment baseurl in epel
  lineinfile: dest=/etc/yum.repos.d/epel.repo regexp="#baseurl=http\:\/\/download\.fedoraproject\.org\/pub\/epel\/7\/\$basearch$"
              line="baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch"
  when: cobbler_epel_too_slow is defined and cobbler_epel_too_slow

- name: comment mirrorlist in epel
  lineinfile: dest=/etc/yum.repos.d/epel.repo regexp="mirrorlist=https\:\/\/mirrors\.fedoraproject\.org\/metalink\?repo=epel-7\&arch=\$basearch$"
              line="#mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
  when: cobbler_epel_too_slow is defined and cobbler_epel_too_slow

- name: install related packages
  yum: name={{ item }} state=present
  with_items:
    - cobbler
    - cobbler-web
    - dnsmasq
    - tftp-server
    - pykickstart
    - openssl

- name: Install dumb init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/bin/dumb-init
    owner: root
    group: root
    mode: 0775


- name: Add entrypoint script
  template:
   src: entrypoint.sh.j2
   dest: /usr/bin/entrypoint.sh
   owner: root
   group: root
   mode: 0775

- name: Cleanup
  shell: yum clean all -y

- name: copy modules.conf
  copy: src=etc/cobbler/modules.conf dest=/etc/cobbler/modules.conf mode=644

- name: generate crypted password
  shell: openssl passwd -1 {{ cobbler_default_password }}
  register: cobbler_default_password_crypted

- name: template settings.j2
  template: src=etc/cobbler/settings.j2 dest=/etc/cobbler/settings

- name: template dnsmasq.template.j2
  template: src=etc/cobbler/dnsmasq.template.j2 dest=/etc/cobbler/dnsmasq.template

- name: template rhel-7-kickstart
  copy:
    src: var/lib/cobbler/kickstarts/rhel-7-kickstart.ks
    dest: /var/lib/cobbler/kickstarts/rhel-7-kickstart.ks
